// src/svelte/components/Avatar.svelte
<script lang="ts">
  import AvatarMarble from './AvatarMarble.svelte'
  import AvatarBeam from './AvatarBeam.svelte'
  import AvatarBauhaus from './AvatarBauhaus.svelte'
  import AvatarPixel from './AvatarPixel.svelte'
  import AvatarRing from './AvatarRing.svelte'
  import AvatarSunset from './AvatarSunset.svelte'

  const AVATAR_VARIANTS: Record<string, any> = {
    marble: AvatarMarble,
    bauhaus: AvatarBauhaus,
    beam: AvatarBeam,
    pixel: AvatarPixel,
    ring: AvatarRing,
    sunset: AvatarSunset,
    geometric: AvatarBeam,
    abstract: AvatarBauhaus,
  }

  const DEFAULT_COLORS = ['#E07A5F', '#3D405B', '#81B29A', '#F4D06F', '#D8A47F']

  let {
    name = 'Clara Barton',
    colors = DEFAULT_COLORS,
    title = false,
    square = false,
    size = 80,
    variant = 'marble',
    ...rest
  }: {
    name?: string
    colors?: string[]
    title?: boolean
    square?: boolean
    size?: number | string
    variant?: string
    [key: string]: unknown
  } = $props()

  const Component = $derived(AVATAR_VARIANTS[variant] ?? AvatarMarble)
</script>

<Component {name} {colors} {title} {square} {size} {...rest} />

// src/vue/components/Avatar.vue
<script setup lang="ts">
import { computed } from 'vue';
import AvatarBauhaus from './avatar-bauhaus.vue';
import AvatarRing from './avatar-ring.vue';
import AvatarPixel from './avatar-pixel.vue';
import AvatarBeam from './avatar-beam.vue';
import AvatarSunset from './avatar-sunset.vue';
import AvatarMarble from './avatar-marble.vue';

interface Props {
  variant?: 'marble' | 'bauhaus' | 'beam' | 'pixel' | 'ring' | 'sunset';
  name?: string;
  colors?: string[];
  title?: boolean;
  square?: boolean;
  size?: number | string;
}

const props = withDefaults(defineProps<Props>(), {
  variant: 'marble',
  colors: () => ['#E07A5F', '#3D405B', '#81B29A', '#F4D06F', '#D8A47F'],
  name: 'Clara Barton',
  title: false,
  square: false,
  size: 80,
});

const AVATAR_VARIANTS = {
  pixel: AvatarPixel,
  bauhaus: AvatarBauhaus,
  ring: AvatarRing,
  beam: AvatarBeam,
  sunset: AvatarSunset,
  marble: AvatarMarble,
  geometric: AvatarBeam,
  abstract: AvatarBauhaus,
} as const;

const AvatarComponent = computed(() => {
  return AVATAR_VARIANTS[props.variant as keyof typeof AVATAR_VARIANTS] || AvatarMarble;
});

const componentProps = computed(() => {
  const { variant, ...rest } = props;
  return rest;
});
</script>

<template>
  <component
    :is="AvatarComponent"
    v-bind="componentProps"
  />
</template>
